version: '3.8'
services:
  fireflyiii:
    # 用于模拟定时任务执行时间（容器内执行），/usr/local/bin/php /var/www/html/artisan firefly-iii:cron --force --date=2023-05-01
    restart: always
    container_name: fireflyiii
    image: fireflyiii/core:latest
    network_mode: host
    environment:
      # https://github.com/firefly-iii/firefly-iii/blob/main/.env.example
      TZ: Asia/Shanghai
      # Key生成方式：head /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | head -c 32 && echo
      APP_KEY: yU6RM6yf9s6F69Su2dl1pVcJxdfu6tG1
      DEFAULT_LANGUAGE: zh_CN
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_DATABASE: fireflyiii
      DB_USERNAME: root
      DB_PASSWORD: root
      # 当使用反向代理时则必须配置
      TRUSTED_PROXIES: "**"
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.qq.com
      MAIL_PORT: 465
      MAIL_FROM: 1319404727@qq.com
      MAIL_USERNAME: 1319404727@qq.com
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: ssl
    volumes:
      - /data/fireflyiii/upload:/var/www/html/storage/upload
      - /data/fireflyiii/export:/var/www/html/storage/export
      - /data/fireflyiii/logs:/var/www/html/storage/logs
      - /data/fireflyiii/config/zh_CN:/var/www/html/resources/lang/zh_CN
      - /data/fireflyiii/config/views/layout/default.twig:/var/www/html/resources/views/layout/default.twig
      - /data/fireflyiii/config/views/partials/page-header.twig:/var/www/html/resources/views/partials/page-header.twig