version: '3.8'
services:
  nifi:
    restart: always
    container_name: nifi
    image: apache/nifi:latest
    ports:
      - "18080:18080"
    environment:
      TZ: Asia/Shanghai
      # default 8000
      JAVA_ARG_DEBUG: 18000
      # default 8080
      NIFI_WEB_HTTP_PORT: 18080
      # default 8443
      NIFI_WEB_HTTPS_PORT: 18443
      NIFI_REMOTE_INPUT_SOCKET_PORT: 10000
      # Docker容器IP
      NIFI_WEB_HTTP_HOST: 172.23.0.2
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      # 密码必须至少为12个字符，否则NiFi将生成一个随机的用户名和密码
      SINGLE_USER_CREDENTIALS_PASSWORD: admin@123456
    volumes: # 授权 chmod -R 777 /data/nifi
      - /data/nifi/logs:/opt/nifi/nifi-current/logs
      - /data/nifi/extensions:/opt/nifi/nifi-current/extensions
      - /data/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - /data/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - /data/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - /data/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository