version: '3.8'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 5s
      timeout: 2s
      retries: 3
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/ssl:/etc/nginx/ssl
      - /data/nginx/logs:/var/log/nginx