version: '3.8'
services:
  appName:
    restart: always
    container_name: appName
    image: openjdk:8-jre-alpine
    network_mode: host
    working_dir: /data
    environment:
      TZ: Asia/Shanghai
    # jar包放至/data/apps/appName目录
    command: java -jar /data/jar/app.jar
    volumes:
      - /data/apps/appName:/data
  appName-skywalking-agent:
    restart: always
    container_name: appName-skywalking-agent
    network_mode: host
    build:
      dockerfile: dockerfile-skywalking-agent
    volumes:
      - /data/apps/appName-sa:/data
