version: '3.8'
services:
  nacos:
    restart: always
    container_name: nacos
    image: nacos/nacos-server:v2.2.0
    network_mode: host
    environment:
      MODE: cluster
      PREFER_HOST_MODE: ip
      NACOS_SERVERS: 172.16.253.112:8848,172.16.253.113:8848,172.16.253.114:8848
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 172.16.253.112
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: oss-config
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
    volumes:
      - /data/nacos/logs/:/home/nacos/logs
      - /data/nacos/conf/cluster.conf:/home/nacos/conf/cluster.conf