version: '3.8'
services:
  redis:
    restart: always
    image: redis:6.2.7
    container_name: redis
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    volumes:
      - /data/redis/conf:/usr/local/etc/redis
      - /data/redis/data:/data
      - /data/redis/logs:/logs