version: '3.8'
services:
  sentinel:
    restart: always
    container_name: sentinel
    network_mode: host
    build:
      context: ./sentinel
      dockerfile: dockerfile
    volumes:
      - /data/sentinel:/data