version: '3.8'
services:
  skywalking-server:
    restart: always
    container_name: skywalking-server
    image: apache/skywalking-oap-server:9.3.0
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      # ------------------cluster------------------
      SW_CLUSTER: nacos
      SW_SERVICE_NAME: skywalking
      SW_CLUSTER_NACOS_HOST_PORT: 172.16.253.112:8844
      SW_CLUSTER_NACOS_NAMESPACE: skywalking-test
      SW_CLUSTER_NACOS_USERNAME: nacos
      SW_CLUSTER_NACOS_PASSWORD: nacos
      # ------------------core------------------
      SW_CORE_REST_HOST: 172.16.253.112
      SW_CORE_GRPC_HOST: 172.16.253.112
      # ------------------storage------------------
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://172.16.253.104:3306/oss-skywalking?createDatabaseIfNotExist=true&rewriteBatchedStatements=true&useSSL=false
      SW_DATA_SOURCE_USER: root
      SW_DATA_SOURCE_PASSWORD: root
      # ------------------config------------------
      SW_CONFIGURATION: nacos
      SW_CONFIG_NACOS_SERVER_ADDR: 172.16.253.112
      SW_CONFIG_NACOS_SERVER_PORT: 8844
      SW_CONFIG_NACOS_SERVER_GROUP: DEFAULT_GROUP
      SW_CONFIG_NACOS_SERVER_NAMESPACE: skywalking-test
      # 同步周期（秒）
      SW_CONFIG_NACOS_PERIOD: 20
      SW_CONFIG_NACOS_USERNAME: nacos
      SW_CONFIG_NACOS_PASSWORD: nacos
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - /data/skywalking/server/ext-libs:/skywalking/ext-libs
      - /data/skywalking/server/ext-config:/skywalking/ext-config
      - /data/skywalking/server/logs:/skywalking/logs
  skywalking-ui:
    restart: always
    container_name: skywalking-ui
    image: apache/skywalking-ui:9.3.0
    network_mode: host
    depends_on:
      skywalking-server:
        condition: service_healthy
    environment:
      TZ: Asia/Shanghai
      SW_SERVER_PORT: 8000
      SW_OAP_ADDRESS: http://172.16.253.112:12800