version: '3.8'
services:
  mariadb:
    restart: always
    image: mariadb:10.6
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb@123456
    volumes:
      - /home/mariadb/conf:/etc/mysql/conf.d
      - /home/mariadb/data:/var/lib/mysql
      - /home/mariadb/log:/var/log/mysql