version: '3.8'
services:
  mysql8:
    restart: always
    container_name: mysql8
    image: mysql:8.0
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      # root用户初始密码
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    command:
      --authentication_policy=mysql_native_password
      --explicit_defaults_for_timestamp=true
    volumes:
      - /data/mysql/conf:/etc/mysql/conf.d
      - /data/mysql/data:/var/lib/mysql
      # logs需要授权
      - /data/mysql/logs:/var/log