version: '3.8'
services:
  minio:
    restart: always
    container_name: minio
    image: minio/minio
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin@1234
    command: server --console-address ":9091" --address ":9090" --config-dir /home/minio http://minio-{1...3}/data{1...2}
    volumes:
      - /data/minio/data1:/data1
      - /data/minio/data2:/data2
      - /data/minio/config:/home/minio
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime